=== MrPalillin/Trabajos-antiguos/TDS/Practica1TDS-dandevi-marmule/Agenda.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT agenda (persona*,grupo*)*>
<!ELEMENT persona (nombre,apellidos?,correo_electronico+,telefono*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT correo_electronico (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (movilPersonal|fijoPersonal|movilTrabajo|fijoTrabajo) "movilPersonal">
<!ATTLIST persona alias ID #REQUIRED>
<!ATTLIST persona grupo IDREF #REQUIRED>
	
<!ELEMENT grupo EMPTY>
<!ATTLIST grupo nombreGrupo CDATA #REQUIRED>
<!ATTLIST grupo miembros IDREFS #IMPLIED>
<!ATTLIST grupo idGrupo ID #REQUIRED>

=== MrPalillin/Trabajos-antiguos/Practica1TDS-dandevi-marmule/Agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "Agenda.dtd" >
<agenda>
  <persona alias="idvalue0" grupo="idvalue0">
    <nombre>Daniel</nombre>
    <apellidos>de Vicente</apellidos>
    <correo_electronico>daniel.vicente@alumnso.uva.es</correo_electronico>
    <telefono tipo="movilPersonal">123456789</telefono>
  </persona>
  <persona alias="idvalue2" grupo="idvalue0">
  	<nombre>Marcos</nombre>
    <apellidos>Mule</apellidos>
    <correo_electronico>marmule@alumnso.uva.es</correo_electronico>
    <telefono tipo="movilTrabajo">147258369</telefono>
  </persona>
  
  <grupo idGrupo="idvalue1" miembros="idvalue0" nombreGrupo=""/>
  
</agenda>
